name: DigiGuess
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.11.5=py36ha569be9_0
- click=6.7=py36hec950be_0
- flask=0.12.2=py36h5658096_0
- freetype=2.8=h12048fb_1
- h5py=2.7.1=py36h39cdac5_0
- hdf5=1.10.1=ha036c08_1
- intel-openmp=2018.0.0=h8158457_8
- itsdangerous=0.24=py36h49fbb8d_1
- jinja2=2.10=py36hd36f9c5_0
- jpeg=9b=he5867d9_2
- keras=2.0.8=py36h39110e4_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgfortran=3.0.1=h93005f0_2
- libpng=1.6.32=hd1e8b91_4
- libprotobuf=3.4.1=h326466f_0
- libtiff=4.0.9=h0dac147_0
- markupsafe=1.0=py36h3a1e703_1
- mkl=2018.0.1=hfbd8650_4
- ncurses=6.0=hd04f020_2
- numpy=1.12.1=py36h8871d66_1
- olefile=0.44=py36ha08bf50_0
- openssl=1.0.2m=h86d3e6a_1
- pillow=4.3.0=py36h96fe3d5_1
- pip=9.0.1=py36h1555ced_4
- protobuf=3.4.1=py36h314970b_0
- python=3.6.3=h5ce8c04_4
- pyyaml=3.12=py36h2ba1e63_1
- readline=7.0=hc1231fa_4
- scipy=1.0.0=py36h1de22e9_0
- setuptools=36.5.0=py36h2134326_0
- six=1.11.0=py36h0e22d5e_1
- sqlite=3.20.1=h7e4c145_2
- tensorflow=1.1.0=np112py36_0
- tk=8.6.7=h35a86e2_3
- werkzeug=0.12.2=py36h168efa1_0
- wheel=0.30.0=py36h5eb2c71_1
- xz=5.2.3=h0278029_2
- yaml=0.1.7=hc338f04_2
- zlib=1.2.11=hf3cbc9b_2
prefix: //anaconda/envs/DigiGuess

